project '/Users/jamesmccarthy/Documents/voicify-ios-sdk/src/voicify-assistant-sdk/voicify-assistant-sdk.xcodeproj'
#source 'https://github.com/weitieda/bottom-sheet.git'
source 'https://github.com/voicifydevs/voicify-ios-sdk-pod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks! :linkage => :static
# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
target 'voicify-assistant-sdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  # Pods for voicify-åassistant-sdk
  pod 'Kingfisher', '~> 7.4.1'
  pod 'BottomSheet', '~> 1.0.6'
end
